type: vertical-stack
cards:
  # - type: custom:button-card
  #   color_type: blank-card
  #   styles:
  #     card:
  #       - height: 50px
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 门口
        icon: 'mdi:door'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/Outdoor
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/Outdoor
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 门厅
        icon: 'mdi:redhat'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/hallway
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/hallway
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

  - type: horizontal-stack
    cards:
      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 餐厅
        icon: 'mdi:noodles'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/diningroom
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/diningroom
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 客厅
        icon: 'mdi:sofa'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/Livingroom
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/Livingroom
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

  - type: horizontal-stack
    cards:
      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 主卧
        icon: 'mdi:bed-king'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/bedroom
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/bedroom
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 次卧
        icon: 'mdi:bed-queen'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/studyroom
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/studyroom
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

  - type: horizontal-stack
    cards:
      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 厨房
        icon: 'mdi:fire'
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/Kitchen
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/Kitchen
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

      - type: custom:button-card
        aspect_ratio: 2/1
        layout: icon_name_state
        size: 50%
        entity: input_boolean.dummy1
        name: 洗手间
        icon: mdi:shower-head
        tap_action:
          action: navigate
          navigation_path: /homekit-infused/bathroom
        hold_action:
          action: navigate
          navigation_path: /homekit-infused/bathroom
        styles:
          card:
            - opacity: 0.8
            - border-radius: var(--border-radius)
            - box-shadow: var(--box-shadow)
          name:
            - font-size: 18px
          state:
            - font-size: 12px
          label:
            - font-size: 12px

  - type: markdown
    cards: null
    style: |
      ha-card { 
          --ha-card-background: "rgba(0, 0, 0, 0.0)";
          --ha-card-box-shadow: 'none';
          font-size: 12px;
          text-align: right;
      }                  
    content: |
      ####  — Designed by 哔哩哔哩@咸味土豆 &nbsp; & &nbsp; HomeAssistant  {{ states('sensor.version_current')}} and hki {{ states('sensor.hki_current_version')}}

  - type: custom:button-card
    color_type: blank-card
    styles:
      card:
        - height: 5px