# lovelace_gen

type: "custom:button-card"
name: "{{ name }}"
icon: "{{ icon }}"
entity: {{ entity }}
aspect_ratio: {{ aspect_ratio|default('2/1') }}
size: 25%
color: auto
show_label: false
show_state: false
show_name: true
tap_action:
  action: call-service
  service: input_select.select_option
  service_data:
    entity_id: {{ entity }}
    option: "{{ option }}"
  haptic: light
styles:
  card:
    - border-radius: var(--border-radius)
    - box-shadow: var(--box-shadow)
    - opacity: 0.8
  name:
    - justify-self: center
    - padding: 0px 10px
    - font-weight: var(--name-font-weight)
    - font-family: var(--font-family) 
    - font-size: var(--name-font-size)
state:
  - value: "{{ option }}"
    styles:
      card:
        - --ha-card-background: var(--button-on-color)
        - opacity: 1.0
      icon:
        - color: var(--paper-item-icon-active-color)
      name:
        - color: var(--paper-item-icon-active-color)
