# lovelace_gen

# card
type: custom:light-popup-card
entity: {{ entity }}
{% if _global.general_config.popups.width is defined %}
brightnessWidth: 110px
switchWidth: 110px
{% else %}
brightnessWidth: 110px
switchWidth: 110px
{% endif %}
{% if _global.general_config.popups.height is defined %}
brightnessHeight: {{ _global.general_config.popups.height }}
switchHeight: {{ _global.general_config.popups.height }}
{% else %}
brightnessHeight: 410px
switchHeight: 410px
{% endif %}
displayType: {{ display_type|default('auto') }}
fullscreen: false
settings: true
settingsPosition: bottom
settingsCard:
  type: custom:more-info-card
  cardOptions:
    entity: {{ entity }}
{% if _global.general_config.popups.actions_per_row is defined %}
actionsInARow: {{ _global.general_config.popups.actions_per_row }}
{% else %}
actionsInARow: 3
{% endif %}
{% if _global.general_config.popups.action_size is defined %}
actionSize: {{ _global.general_config.popups.action_size }}
{% else %}
actionSize: 30px
{% endif %}
{% if _global.general_config.popups.slider_colored_by_light is defined %}
sliderColoredByLight: {{ _global.general_config.popups.slider_colored_by_light }}
{% else %}
sliderColoredByLight: true
{% endif %}
actions:
  {% if _global.general_config.popups.rgb_popup is defined %}
  {% for content in _global.general_config.popups.rgb_popup %}
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: {{ content.rgb_color }}
    color: '{{ content.hex_color }}'
  {% endfor %}
  {% else %}
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: [255, 136, 0]
    color: '#ff8800'
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: [255, 0, 95]
    color: '#ff005f'
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: [40, 255, 0]
    color: '#28ff00'
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: [0, 160, 255]
    color: '#00a0ff'
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: [131, 0, 255]
    color: '#8300ff'
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      rgb_color: [3, 0, 255]
    color: '#0300ff'
  {% endif %}